/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClerkPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FromEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FromEmailPw": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}