import preact from 'eslint-config-preact';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';

// eslint-config-preact@2.0.0 already ships a flat-config array
// (ESM `export default [...]` with `languageOptions`/`plugins` objects),
// so it is spread directly rather than wrapped in FlatCompat — FlatCompat
// is only for translating legacy eslintrc-style shareable configs, and
// feeding it an already-flat config would mangle it.
//
// The preact config parses with @babel/eslint-parser (JS/JSX only). This
// project's source is TypeScript (.ts/.tsx), so a later block re-points the
// parser to @typescript-eslint/parser for those files. All preact rules
// (@eslint/js recommended + eslint-plugin-react + react-hooks) still apply
// because the preact config block has no `files` restriction; only the
// parser is overridden here.
export default [
	...preact,
	{
		files: ['**/*.ts', '**/*.tsx'],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				ecmaVersion: 'latest',
				sourceType: 'module',
				ecmaFeatures: { jsx: true },
			},
		},
		plugins: {
			'@typescript-eslint': tsPlugin,
		},
		rules: {
			// Core no-undef can't resolve TS-only names (e.g. `React` in type
			// positions like React.JSX, or DOM lib types like
			// IntersectionObserverInit). typescript-eslint's documented guidance
			// is to disable it for TS files — tsc owns undefined-name checking.
			'no-undef': 'off',
			// Core no-unused-vars misreads params in TS function *type*
			// signatures (e.g. `onChange: (value: T) => void`) as unused vars.
			// Replace it with the TS-aware equivalent, which understands types.
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': 'error',
		},
	},
	{
		// sst-env.d.ts is generated by SST — not ours to lint.
		ignores: ['dist/**', 'node_modules/**', 'src/sst-env.d.ts'],
	},
];
